# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model_ import Model
from api import util


class FilePayloadUpdateInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, file_id: str=None, file_payload: str=None):  # noqa: E501
        """FilePayloadUpdateInput - a model defined in Swagger

        :param file_id: The file_id of this FilePayloadUpdateInput.  # noqa: E501
        :type file_id: str
        :param file_payload: The file_payload of this FilePayloadUpdateInput.  # noqa: E501
        :type file_payload: str
        """
        self.swagger_types = {
            'file_id': str,
            'file_payload': str
        }

        self.attribute_map = {
            'file_id': 'file_id',
            'file_payload': 'file_payload'
        }
        self._file_id = file_id
        self._file_payload = file_payload

    @classmethod
    def from_dict(cls, dikt) -> 'FilePayloadUpdateInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FilePayloadUpdateInput of this FilePayloadUpdateInput.  # noqa: E501
        :rtype: FilePayloadUpdateInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file_id(self) -> str:
        """Gets the file_id of this FilePayloadUpdateInput.


        :return: The file_id of this FilePayloadUpdateInput.
        :rtype: str
        """
        return self._file_id

    @file_id.setter
    def file_id(self, file_id: str):
        """Sets the file_id of this FilePayloadUpdateInput.


        :param file_id: The file_id of this FilePayloadUpdateInput.
        :type file_id: str
        """
        if file_id is None:
            raise ValueError("Invalid value for `file_id`, must not be `None`")  # noqa: E501

        self._file_id = file_id

    @property
    def file_payload(self) -> str:
        """Gets the file_payload of this FilePayloadUpdateInput.


        :return: The file_payload of this FilePayloadUpdateInput.
        :rtype: str
        """
        return self._file_payload

    @file_payload.setter
    def file_payload(self, file_payload: str):
        """Sets the file_payload of this FilePayloadUpdateInput.


        :param file_payload: The file_payload of this FilePayloadUpdateInput.
        :type file_payload: str
        """
        if file_payload is None:
            raise ValueError("Invalid value for `file_payload`, must not be `None`")  # noqa: E501

        self._file_payload = file_payload
