# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model_ import Model
from api import util


class WorkspaceResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, workspace_id: str=None, name: str=None, created_at: str=None, updated_at: str=None, design_files: List[str]=None):  # noqa: E501
        """WorkspaceResponse - a model defined in Swagger

        :param workspace_id: The workspace_id of this WorkspaceResponse.  # noqa: E501
        :type workspace_id: str
        :param name: The name of this WorkspaceResponse.  # noqa: E501
        :type name: str
        :param created_at: The created_at of this WorkspaceResponse.  # noqa: E501
        :type created_at: str
        :param updated_at: The updated_at of this WorkspaceResponse.  # noqa: E501
        :type updated_at: str
        :param design_files: The design_files of this WorkspaceResponse.  # noqa: E501
        :type design_files: List[str]
        """
        self.swagger_types = {
            'workspace_id': str,
            'name': str,
            'created_at': str,
            'updated_at': str,
            'design_files': List[str]
        }

        self.attribute_map = {
            'workspace_id': 'workspace_id',
            'name': 'name',
            'created_at': 'created_at',
            'updated_at': 'updated_at',
            'design_files': 'design_files'
        }
        self._workspace_id = workspace_id
        self._name = name
        self._created_at = created_at
        self._updated_at = updated_at
        self._design_files = design_files

    @classmethod
    def from_dict(cls, dikt) -> 'WorkspaceResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WorkspaceResponse of this WorkspaceResponse.  # noqa: E501
        :rtype: WorkspaceResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def workspace_id(self) -> str:
        """Gets the workspace_id of this WorkspaceResponse.


        :return: The workspace_id of this WorkspaceResponse.
        :rtype: str
        """
        return self._workspace_id

    @workspace_id.setter
    def workspace_id(self, workspace_id: str):
        """Sets the workspace_id of this WorkspaceResponse.


        :param workspace_id: The workspace_id of this WorkspaceResponse.
        :type workspace_id: str
        """

        self._workspace_id = workspace_id

    @property
    def name(self) -> str:
        """Gets the name of this WorkspaceResponse.


        :return: The name of this WorkspaceResponse.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this WorkspaceResponse.


        :param name: The name of this WorkspaceResponse.
        :type name: str
        """

        self._name = name

    @property
    def created_at(self) -> str:
        """Gets the created_at of this WorkspaceResponse.


        :return: The created_at of this WorkspaceResponse.
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: str):
        """Sets the created_at of this WorkspaceResponse.


        :param created_at: The created_at of this WorkspaceResponse.
        :type created_at: str
        """

        self._created_at = created_at

    @property
    def updated_at(self) -> str:
        """Gets the updated_at of this WorkspaceResponse.


        :return: The updated_at of this WorkspaceResponse.
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: str):
        """Sets the updated_at of this WorkspaceResponse.


        :param updated_at: The updated_at of this WorkspaceResponse.
        :type updated_at: str
        """

        self._updated_at = updated_at

    @property
    def design_files(self) -> List[str]:
        """Gets the design_files of this WorkspaceResponse.


        :return: The design_files of this WorkspaceResponse.
        :rtype: List[str]
        """
        return self._design_files

    @design_files.setter
    def design_files(self, design_files: List[str]):
        """Sets the design_files of this WorkspaceResponse.


        :param design_files: The design_files of this WorkspaceResponse.
        :type design_files: List[str]
        """

        self._design_files = design_files
