version: "3"
services:
    
    s3local:
      image: minio/minio
      ports:
        - "9000:9000"
        - "9001:9001"
      volumes:
        - mino_data:/data/s3
      environment:
        - MINIO_ACCESS_KEY=minio
        - MINIO_SECRET_KEY=minio123
      command: server /data/s3 --console-address ":9001"
      restart: unless-stopped

    broker:
      image: redis:latest
      container_name: realtime-comm-server
      ports:
        - "6379:6379"

    backend_database:
      image: mongo:latest
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword
      ports:
        - 27017:27017
      volumes:
        - mongodb_data_container:/data/db

    worker:
      build: 
        context: .
        dockerfile: ./job-runner/Dockerfile
      container_name: demo_worker
      command: celery --app=simple worker --loglevel=info
      volumes:
        - .:/usr/src
      environment:
        - CELERY_BROKER_URL=redis://broker:6379
        # - CELERY_RESULT_BACKEND=db+postgresql://dbc:dbc@backend:5432/celery
      depends_on:
        - broker
        - backend_database
        - s3local


volumes:
  mongodb_data_container:
  mino_data: