import os

# File IO Directories
FLASK_UPLOADS_DIRECTORY = os.path.abspath("/tmp/uploads/")
FLASK_DOWNLOADS_DIRECTORY = os.path.abspath("/tmp/downloads/")

# SOCKETIO REDIS CONFIGURATION
SOCKETIO_REDIS_HOST = os.getenv('SOCKETIO_REDIS_HOST')
SOCKETIO_REDIS_PORT = int(os.getenv('SOCKETIO_REDIS_PORT', 6379))


# CELERY SETTINGS
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'


# CELERY MONGO SETTINGS
MONGODB_USER = os.getenv('MONGO_INITDB_ROOT_USERNAME', 'root')
MONGODB_PASSWORD = os.getenv('MONGO_INITDB_ROOT_PASSWORD', 'rootpassword')
MONGODB_INITDB_NAME = os.getenv('MONGO_INITDB_NAME', 'neptune')
MONGO_HOST = os.getenv('MONGO_HOST', 'localhost')
MONGO_PORT = int(os.getenv('MONGO_PORT', 27017))

NEPTUNE_MONGODB_DBNAME = os.getenv('NEPTUNE_MONGODB_DBNAME', 'neptune')

CELERY_BACKEND_URL = f'mongodb://{MONGODB_USER}:{MONGODB_PASSWORD}@{MONGO_HOST}:{MONGO_PORT}/{MONGODB_INITDB_NAME}'

CELERY_TASKMETA_COLLECTION = os.getenv('CELERY_TASK_META_COLLECTION_NAME', 'celery_taskmeta')

# AWS S3 SETTINGS
AWS_S3_BUCKET_NAME = os.getenv('AWS_S3_BUCKET_NAME', 'fluigi')
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', "minio")
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', "minio123")
AWS_ENDPOINT_URL = os.getenv('AWS_ENDPOINT_URL', "http://localhost:9000")
