# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fluigi_cloud.models.base_model_ import Model
from fluigi_cloud import util


class WorkspaceInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, workspace_id: str=None):  # noqa: E501
        """WorkspaceInput - a model defined in Swagger

        :param workspace_id: The workspace_id of this WorkspaceInput.  # noqa: E501
        :type workspace_id: str
        """
        self.swagger_types = {
            'workspace_id': str
        }

        self.attribute_map = {
            'workspace_id': 'workspace_id'
        }
        self._workspace_id = workspace_id

    @classmethod
    def from_dict(cls, dikt) -> 'WorkspaceInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WorkspaceInput of this WorkspaceInput.  # noqa: E501
        :rtype: WorkspaceInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def workspace_id(self) -> str:
        """Gets the workspace_id of this WorkspaceInput.


        :return: The workspace_id of this WorkspaceInput.
        :rtype: str
        """
        return self._workspace_id

    @workspace_id.setter
    def workspace_id(self, workspace_id: str):
        """Sets the workspace_id of this WorkspaceInput.


        :param workspace_id: The workspace_id of this WorkspaceInput.
        :type workspace_id: str
        """
        if workspace_id is None:
            raise ValueError("Invalid value for `workspace_id`, must not be `None`")  # noqa: E501

        self._workspace_id = workspace_id
